import type { Hotel, Room, Reservation } from "./types"

export const hotels: Hotel[] = [
    {
        id: "1",
        name: "Hotel Paraíso Tropical",
        address: "Av. Costera 123",
        country: "México",
        location: "Cancún, Quintana Roo",
        description: "Disfruta de playas paradisíacas y servicios de lujo en nuestro resort frente al mar Caribe.",
        image: "/luxury-cancun-resort.png",
        pricePerNight: 150,
        rating: 4.8,
        email: "info@paraiso.com",
        phone: "+52 998 123 4567",
    },
    {
        id: "2",
        name: "Grand Hotel Europa",
        address: "Calle Mayor 45",
        country: "España",
        location: "Madrid, España",
        description: "Hotel boutique en el corazón de Madrid, con arquitectura clásica y comodidades modernas.",
        image: "/elegant-hotel-madrid-architecture.jpg",
        pricePerNight: 120,
        rating: 4.6,
        email: "reservas@grandeuropa.es",
        phone: "+34 91 234 5678",
    },
    {
        id: "3",
        name: "Mountain View Lodge",
        address: "Camino Alpino 789",
        country: "Suiza",
        location: "Zermatt, Suiza",
        description: "Refugio alpino con vistas espectaculares al Matterhorn y acceso directo a pistas de esquí.",
        image: "/swiss-alps-mountain-lodge-snow.jpg",
        pricePerNight: 200,
        rating: 4.9,
        email: "info@mountainview.ch",
        phone: "+41 27 966 1234",
    },
    {
        id: "4",
        name: "Urban Boutique Hotel",
        address: "5th Avenue 234",
        country: "Estados Unidos",
        location: "Nueva York, NY",
        description: "Hotel moderno en Manhattan con diseño contemporáneo y fácil acceso a las principales atracciones.",
        image: "/modern-boutique-hotel-new-york-city.jpg",
        pricePerNight: 180,
        rating: 4.5,
        email: "stay@urbanboutique.com",
        phone: "+1 212 555 0123",
    },
    {
        id: "5",
        name: "Sakura Garden Hotel",
        address: "Shibuya 2-3-4",
        country: "Japón",
        location: "Tokio, Japón",
        description: "Fusión perfecta entre tradición japonesa y lujo moderno en el vibrante distrito de Shibuya.",
        image: "/japanese-hotel-tokyo-cherry-blossoms.jpg",
        pricePerNight: 160,
        rating: 4.7,
        email: "info@sakuragarden.jp",
        phone: "+81 3 1234 5678",
    },
    {
        id: "6",
        name: "Coastal Breeze Resort",
        address: "Ocean Drive 567",
        country: "Australia",
        location: "Gold Coast, Queensland",
        description: "Resort frente al mar con piscinas infinitas, spa de clase mundial y restaurantes gourmet.",
        image: "/luxury-beach-resort-australia-ocean.jpg",
        pricePerNight: 190,
        rating: 4.8,
        email: "bookings@coastalbreeze.au",
        phone: "+61 7 5555 1234",
    },
]

export const mockRooms: Room[] = [
    // Hotel Paraíso Tropical
    {
        id: "r1",
        roomNumber: "101",
        hotelId: "1",
        capacity: 2,
        available: true,
        rating: 4.8,
        pricePerNight: 150,
        description: "Habitación doble con vista al mar",
    },
    {
        id: "r2",
        roomNumber: "102",
        hotelId: "1",
        capacity: 4,
        available: true,
        rating: 4.9,
        pricePerNight: 250,
        description: "Suite familiar con balcón privado",
    },
    {
        id: "r3",
        roomNumber: "201",
        hotelId: "1",
        capacity: 2,
        available: false,
        rating: 4.7,
        pricePerNight: 180,
        description: "Habitación premium con jacuzzi",
    },

    // Grand Hotel Europa
    {
        id: "r4",
        roomNumber: "301",
        hotelId: "2",
        capacity: 2,
        available: true,
        rating: 4.6,
        pricePerNight: 120,
        description: "Habitación clásica con decoración europea",
    },
    {
        id: "r5",
        roomNumber: "302",
        hotelId: "2",
        capacity: 3,
        available: true,
        rating: 4.7,
        pricePerNight: 180,
        description: "Suite junior con sala de estar",
    },

    // Mountain View Lodge
    {
        id: "r6",
        roomNumber: "A1",
        hotelId: "3",
        capacity: 2,
        available: true,
        rating: 4.9,
        pricePerNight: 200,
        description: "Cabaña con chimenea y vista a la montaña",
    },
    {
        id: "r7",
        roomNumber: "A2",
        hotelId: "3",
        capacity: 4,
        available: true,
        rating: 5.0,
        pricePerNight: 350,
        description: "Suite alpina de lujo con sauna privada",
    },

    // Urban Boutique Hotel
    {
        id: "r8",
        roomNumber: "1501",
        hotelId: "4",
        capacity: 2,
        available: true,
        rating: 4.5,
        pricePerNight: 180,
        description: "Habitación moderna con vista a la ciudad",
    },
    {
        id: "r9",
        roomNumber: "1502",
        hotelId: "4",
        capacity: 2,
        available: false,
        rating: 4.6,
        pricePerNight: 220,
        description: "Suite ejecutiva con oficina",
    },

    // Sakura Garden Hotel
    {
        id: "r10",
        roomNumber: "401",
        hotelId: "5",
        capacity: 2,
        available: true,
        rating: 4.7,
        pricePerNight: 160,
        description: "Habitación estilo japonés tradicional",
    },
    {
        id: "r11",
        roomNumber: "402",
        hotelId: "5",
        capacity: 3,
        available: true,
        rating: 4.8,
        pricePerNight: 240,
        description: "Suite con jardín zen privado",
    },

    // Coastal Breeze Resort
    {
        id: "r12",
        roomNumber: "B101",
        hotelId: "6",
        capacity: 2,
        available: true,
        rating: 4.8,
        pricePerNight: 190,
        description: "Habitación deluxe frente al mar",
    },
    {
        id: "r13",
        roomNumber: "B102",
        hotelId: "6",
        capacity: 4,
        available: true,
        rating: 4.9,
        pricePerNight: 320,
        description: "Villa familiar con piscina privada",
    },
]

export const rooms = mockRooms

export const mockReservations: Reservation[] = [
    {
        id: "res1",
        hotelName: "Hotel Paraíso Tropical",
        roomNumber: "201",
        orderNumber: "ORD-2025-001",
        username: "martinlopez_05",
        checkInDate: "2025-06-15",
        checkOutDate: "2025-06-20",
        price: 900,
        registrationDate: "2025-05-10",
    },
    {
        id: "res2",
        hotelName: "Grand Hotel Europa",
        roomNumber: "302",
        orderNumber: "ORD-2025-002",
        username: "martinlopez_05",
        checkInDate: "2025-07-01",
        checkOutDate: "2025-07-05",
        price: 720,
        registrationDate: "2025-05-15",
    },
]

export const reservations = mockReservations
