
eureka.client.enabled=false
spring.cloud.discovery.enabled=false


spring.rabbitmq.listener.simple.auto-startup=false

logging.level.org.mongodb.driver=WARN
logging.level.org.springframework.data.mongodb=DEBUG