name: CI - Microservices Tests

on:
  push:
    branches:
      - main
      - master
      - "feat/**"
      - "test/**"
      - "fix/**"
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice:
          - msvc-hotels
          - msvc-payments
          - msvc-reservations
          - msvc-reviews
          - msvc-rooms
          - msvc-users
      fail-fast: false

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y Correr los Tests de ${{ matrix.microservice }}
        run: mvn clean verify
        working-directory: ./Backend/hotel-reservation-system/${{ matrix.microservice }}
